owner: oknors
repo: status
user-agent: OKNObot

# Add your sites here
sites:
  - name: OKNO
    url: https://okno.rs
  - name: ParallelCoin Info
    url: https://parallelcoin.info
  - name: ParallelCoin Status
    url: https://status.parallelcoin.info
  - name: ParallelCoin Documetation
    url: https://docs.parallelcoin.info
  - name: com-http.up
    url: https://com-http.us
  - name: com-http.org
    url: https://com-http.org
  - name: Secret Site
    url: $SECRET_SITE

# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
  - type: slack
    channel: C01dddd9S9Y
assignees:
  - AnandChowdhary

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  cname: status.okno.rs
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: StatusOKNO
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
